/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICakeNFTMarketplaceInterface extends ethers.utils.Interface {
  functions: {
    "acceptOffer(address,uint256,uint256)": FunctionFragment;
    "auction(address,uint256,uint256,uint256)": FunctionFragment;
    "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "bid(address,uint256,uint256)": FunctionFragment;
    "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "buy(address,uint256)": FunctionFragment;
    "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "cancelAuction(address,uint256)": FunctionFragment;
    "cancelOffer(address,uint256,uint256)": FunctionFragment;
    "cancelSale(address,uint256)": FunctionFragment;
    "checkAuction(address,uint256)": FunctionFragment;
    "checkSelling(address,uint256)": FunctionFragment;
    "claim(address,uint256)": FunctionFragment;
    "offer(address,uint256,uint256)": FunctionFragment;
    "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "sell(address,uint256,uint256)": FunctionFragment;
    "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auction",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bid",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bidWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSale",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuction",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSelling",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offer",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellWithPermit",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auctionWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bidWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSelling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellWithPermit",
    data: BytesLike
  ): Result;

  events: {
    "AcceptOffer(address,uint256,uint256,address)": EventFragment;
    "Auction(address,uint256,address,uint256,uint256)": EventFragment;
    "Bid(address,uint256,address,uint256)": EventFragment;
    "Buy(address,uint256,address,uint256)": EventFragment;
    "CancelAuction(address,uint256,address)": EventFragment;
    "CancelOffer(address,uint256,uint256,address)": EventFragment;
    "CancelSale(address,uint256,address)": EventFragment;
    "Claim(address,uint256,address,uint256)": EventFragment;
    "Offer(address,uint256,uint256,address,uint256)": EventFragment;
    "Sell(address,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AcceptOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Auction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Bid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelAuction"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelOffer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelSale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Offer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sell"): EventFragment;
}

export class ICakeNFTMarketplace extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICakeNFTMarketplaceInterface;

  functions: {
    acceptOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "acceptOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    auction(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "auction(address,uint256,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    auctionWithPermit(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bid(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bid(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    bidWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buy(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buy(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyWithPermit(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelSale(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelSale(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkSelling(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkSelling(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claim(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    offer(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "offer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    offerWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sell(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sell(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  acceptOffer(
    nft: string,
    nftId: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "acceptOffer(address,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  auction(
    nft: string,
    nftId: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "auction(address,uint256,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  auctionWithPermit(
    nft: string,
    nftId: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
    nft: string,
    nftId: BigNumberish,
    startPrice: BigNumberish,
    endBlock: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bid(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bid(address,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  bidWithPermit(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buy(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buy(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyWithPermit(
    nft: string,
    nftId: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)"(
    nft: string,
    nftId: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelAuction(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelAuction(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelOffer(
    nft: string,
    nftId: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelOffer(address,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    offerId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelSale(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelSale(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkAuction(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkAuction(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkSelling(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkSelling(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claim(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(address,uint256)"(
    nft: string,
    nftId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  offer(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "offer(address,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  offerWithPermit(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sell(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sell(address,uint256,uint256)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellWithPermit(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
    nft: string,
    nftId: BigNumberish,
    price: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "acceptOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    auction(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "auction(address,uint256,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    auctionWithPermit(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    bid(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bid(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bidWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buy(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "buy(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    buyWithPermit(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelSale(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelSale(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    checkSelling(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "checkSelling(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    claim(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "claim(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    offer(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "offer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sell(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sell(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sellWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AcceptOffer(
      nft: string | null,
      nftId: BigNumberish | null,
      offerId: BigNumberish | null,
      acceptor: null
    ): EventFilter;

    Auction(
      nft: string | null,
      nftId: BigNumberish | null,
      owner: string | null,
      startPrice: null,
      endBlock: null
    ): EventFilter;

    Bid(
      nft: string | null,
      nftId: BigNumberish | null,
      bidder: string | null,
      price: null
    ): EventFilter;

    Buy(
      nft: string | null,
      nftId: BigNumberish | null,
      buyer: string | null,
      price: null
    ): EventFilter;

    CancelAuction(
      nft: string | null,
      nftId: BigNumberish | null,
      owner: string | null
    ): EventFilter;

    CancelOffer(
      nft: string | null,
      nftId: BigNumberish | null,
      offerId: BigNumberish | null,
      offeror: null
    ): EventFilter;

    CancelSale(
      nft: string | null,
      nftId: BigNumberish | null,
      owner: string | null
    ): EventFilter;

    Claim(
      nft: string | null,
      nftId: BigNumberish | null,
      bidder: string | null,
      price: null
    ): EventFilter;

    Offer(
      nft: string | null,
      nftId: BigNumberish | null,
      offerId: BigNumberish | null,
      offeror: null,
      price: null
    ): EventFilter;

    Sell(
      nft: string | null,
      nftId: BigNumberish | null,
      owner: string | null,
      price: null
    ): EventFilter;
  };

  estimateGas: {
    acceptOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "acceptOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    auction(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "auction(address,uint256,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    auctionWithPermit(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bid(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bid(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    bidWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buy(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buy(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyWithPermit(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelSale(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelSale(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkSelling(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkSelling(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claim(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "claim(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    offer(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "offer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    offerWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sell(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sell(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "acceptOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    auction(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "auction(address,uint256,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    auctionWithPermit(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "auctionWithPermit(address,uint256,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      startPrice: BigNumberish,
      endBlock: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bid(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bid(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    bidWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bidWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buy(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buy(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyWithPermit(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyWithPermit(address,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelOffer(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelOffer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      offerId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelSale(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelSale(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkAuction(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkAuction(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkSelling(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkSelling(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claim(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(address,uint256)"(
      nft: string,
      nftId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    offer(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "offer(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    offerWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "offerWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sell(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sell(address,uint256,uint256)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellWithPermit(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellWithPermit(address,uint256,uint256,uint256,uint8,bytes32,bytes32)"(
      nft: string,
      nftId: BigNumberish,
      price: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
